
#
# Frontend deployment, service and ingress
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-client
  labels:
    app: project-client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: project-client
  template:
    metadata:
      labels:
        app: project-client
    spec:
      containers:
      - name: project-server
        image: drchung5/tldp-client
---

kind: Service
apiVersion: v1
metadata:
  name: project-client
  labels:
    app: project-client
spec:
  #type: NodePort
  selector:
    app: project-client
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: project-client-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: project-client
            port:
              number: 80
---